name: SATDuelist
options:
  bundleIdPrefix: com.eeshmajithia
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: YES

targets:
  SATDuelist:
    type: application
    platform: iOS
    sources:
      - path: SATDuelist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.eeshmajithia.satduelist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    scheme:
      gatherCoverageData: false
